-- TradeXBot schema for Supabase Postgres.
-- Run this in the Supabase Dashboard -> SQL Editor, then set AUTO_CREATE_TABLES=false.
-- Mirrors the SQLAlchemy models in app/models/.

-- Enum types (names/values match SQLAlchemy's defaults so the ORM stays compatible).
do $$ begin
  create type transactiontype as enum ('deposit', 'withdrawal', 'referral_bonus');
exception when duplicate_object then null; end $$;

do $$ begin
  create type transactionstatus as enum ('pending', 'approved', 'rejected');
exception when duplicate_object then null; end $$;

create table if not exists users (
  id              bigint generated by default as identity primary key,
  email           varchar(255) not null unique,
  full_name       varchar(120) not null,
  hashed_password varchar(255) not null,
  is_active       boolean not null default true,
  is_admin        boolean not null default false,
  balance         numeric(18, 2) not null default 0,
  referral_code   varchar(12) not null unique,
  referred_by_id  bigint references users(id),
  created_at      timestamptz not null default now(),
  password_reset_otp varchar(12),
  password_reset_expires_at timestamptz
);
create index if not exists ix_users_email on users (email);
create index if not exists ix_users_referral_code on users (referral_code);

create table if not exists transactions (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references users(id) on delete cascade,
  type        transactiontype not null,
  status      transactionstatus not null default 'pending',
  amount      numeric(18, 2) not null,
  note        varchar(255),
  screenshot_data text,
  account_name varchar(120),
  wallet_address varchar(255),
  network varchar(50),
  created_at  timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists ix_transactions_user_id on transactions (user_id);

create table if not exists referrals (
  id           bigint generated by default as identity primary key,
  referrer_id  bigint not null references users(id),
  referred_id  bigint not null references users(id) unique,
  bonus_amount numeric(18, 2) not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists ix_referrals_referrer_id on referrals (referrer_id);

-- Note on RLS: this app talks to Postgres through the FastAPI backend using the
-- database (postgres) role, with its own JWT auth in app/api/deps.py — it does NOT
-- use Supabase Auth or the anon/public client. So Row Level Security is not required
-- for correctness here. If you ever expose these tables to the Supabase client SDK
-- directly, enable RLS and add policies before doing so.
